import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import login from '@/lib/store/features/profile/profileSlice'
import getAuthData from "@/lib/actions/getAuthData";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  
  children,

}: Readonly<{
  children: React.ReactNode;
}>

) {

  return (
    <html lang="en">
      <body>
      <StoreProvider>
        <NavBar/>
        {children}
        {/* <Footer/> */}
      </StoreProvider>
      
      </body>
    </html>
  );
}
